=== jorgecidc/html-css/PR13/ejemplos/personas.dtd
<!ELEMENT persona (nombre,apellidos,fecha-de-nacimiento,ciudad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT fecha-de-nacimiento (dia,mes,anno)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>

=== jorgecidc/html-css/PR13/ejemplos/personas.xml
<!DOCTYPE persona SYSTEM "personas.dtd">
<persona>
    <nombre>Elsa</nombre>
    <apellidos>Zambrano</apellidos>
    <fecha-de-nacimiento>
            <dia>18</dia>
            <mes>6</mes>
            <anno>1996</anno>
    </fecha-de-nacimiento>
    <ciudad>Pamplona</ciudad>
</persona>
