=== jorgecidc/html-css/PR13/cds.dtd
<!ELEMENT catalogo_cd (disco+)>
<!ELEMENT disco (artista,anno,precio,ncanciones)>
<!ATTLIST disco titulo CDATA #REQUIRED>
<!ELEMENT artista (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT ncanciones (#PCDATA)>

=== jorgecidc/html-css/PR13/cds.xml
<!DOCTYPE catalogo_cd SYSTEM "cds.dtd">
<catalogo_cd>
    <disco titulo="yo minoria absoluta">
        <artista>extremoduro</artista> 
        <anno>2002</anno>       
        <precio>15</precio>
        <ncanciones>10</ncanciones>
    </disco>
    <disco titulo="canciones que gemias tu">
        <artista>calenton</artista>
        <anno>2017</anno>
        <precio>12</precio>
        <ncanciones>7</ncanciones>
    </disco>
</catalogo_cd>
