=== jorgecidc/html-css/PR13/existenciasV1.dtd
<!ELEMENT existencias (fecha,hora,producto+)>
<!ELEMENT fecha (dia,mes,anno)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anno (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT producto (sku,nombre,stock)>
<!ELEMENT sku (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT stock (actual,minimo,maximo)>
<!ELEMENT actual (#PCDATA)>
<!ELEMENT minimo (#PCDATA)>
<!ELEMENT maximo (#PCDATA)>

=== jorgecidc/html-css/PR13/existenciasV1.xml
<!DOCTYPE existencias SYSTEM "existenciasV1.dtd">
<existencias>
    <fecha>
        <dia>14</dia>
        <mes>10</mes>
        <anno>2022</anno>  
    </fecha>
    
    <hora>17:00</hora>

    <producto>
         <sku>00651</sku>
         <nombre>produdcto 1</nombre>
         <stock>
            <actual>234</actual>
            <minimo>2</minimo>
            <maximo>500</maximo>
         </stock>
    </producto>

    <producto>
        <sku>00652</sku>
        <nombre>producto 2</nombre>
        <stock>
            <actual>256</actual>
            <minimo>6</minimo>
            <maximo>500</maximo>
         </stock>
   </producto>

   <producto>
        <sku>00653</sku>
        <nombre>producto 3</nombre>
        <stock>
            <actual>567</actual>
            <minimo>100</minimo>
            <maximo>800</maximo>
     </stock>
</producto>

</existencias>
