=== jorgecidc/html-css/PR13/horarios.dtd
<!ELEMENT horario (nombre,url,grupo,modulo,grado)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT grupo (denominacion,nombre_grado,modulos,dias)>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT nombre_grado (#PCDATA)>
<!ELEMENT modulos (asignatura+,tutor?)>
<!ELEMENT asignatura (nombre,abreviatura,profesor,horas)>
<!ELEMENT abreviatura (#PCDATA)>
<!ELEMENT profesor (#PCDATA)>
<!ELEMENT horas (#PCDATA)>
<!ELEMENT tutor (#PCDATA)>
<!ELEMENT dias (dia+)>
<!ELEMENT dia (nombre,hora+)>
<!ELEMENT hora (numero?,hora_ini?,hora-fin?,modulo?,recreo?)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT hora_ini (#PCDATA)>
<!ELEMENT hora-fin (#PCDATA)>
<!ELEMENT modulo (#PCDATA|denominacion|nombre_grado|asignatura|modulos|tutor|dias)*>
<!ELEMENT recreo (#PCDATA)>
<!ELEMENT grado (denominacion,nombre_grado,asignatura,modulos,tutor,dias)>

=== jorgecidc/html-css/PR13/horarios.xml
<!DOCTYPE horario SYSTEM "horarios.dtd">
<horario>
    <nombre>IES VALLE DEL JERTE</nombre>
    <url>https://iesvallejertepla.educarex.es/</url>
    <grupo>
        <denominacion>1ºASIR</denominacion>
        <nombre_grado>administracion de sistemas informaticos en red</nombre_grado>
        <modulos>
        <asignatura>
            <nombre>implantacion de sistemas operativos</nombre>
           <abreviatura>ISO</abreviatura>
           <profesor>antonio berrocal</profesor>
           <horas>224h</horas> 
        </asignatura>
        <asignatura>
            <nombre>planificacion y administracion de redes</nombre>
           <abreviatura>PARE</abreviatura>
           <profesor>marian valdera</profesor>
           <horas>224h</horas> 
        </asignatura>
        <asignatura>
            <nombre>fundamentos de hardware</nombre>
           <abreviatura>FHW</abreviatura>
           <profesor>fernando torrecilla</profesor>
           <horas>96h</horas> 
        </asignatura>
        <asignatura>
            <nombre>gestion de base de datos</nombre>
           <abreviatura>GBD</abreviatura>
           <profesor>marcos fernandez</profesor>
           <horas>192h</horas> 
        </asignatura>
        <asignatura>
            <nombre>lenguaje de marca y sistemas gestion de inf</nombre>
           <abreviatura>LMSGI</abreviatura>
           <profesor>antonio berrocal</profesor>
           <horas>128h</horas> 
        </asignatura>
        <asignatura>
            <nombre>formacion y orientacion laboral</nombre>
           <abreviatura>FOL</abreviatura>
           <profesor>fatima hontiveros</profesor>
           <horas>96h</horas> 
        </asignatura>
        <tutor>fatima hontiveros almaraz</tutor>
    </modulos>
        <dias>
        <dia>
            <nombre>lunes</nombre>
            <hora>
                <numero>1</numero>
                <hora_ini>15:20</hora_ini>
                <hora-fin>16:15</hora-fin>
                <modulo>ISO</modulo>
            </hora>
            <hora>
                <numero>2</numero>
                <hora_ini>16:15</hora_ini>
                <hora-fin>17:10</hora-fin>
                <modulo>LMSGI</modulo>
            </hora>            <hora>
                <numero>3</numero>
                <hora_ini>17:10</hora_ini>
                <hora-fin>18:05</hora-fin>
                <modulo>FOL</modulo>
            </hora>
            <hora>
                <recreo>18:05-18:25</recreo>
            </hora>
            <hora>
                <numero>4</numero>
                <hora_ini>18:25</hora_ini>
                <hora-fin>19:20</hora-fin>
                <modulo>GBD</modulo>
            </hora>
            <hora>
                <numero>5</numero>
                <hora_ini>19:20</hora_ini>
                <hora-fin>20:15</hora-fin>
                <modulo>GBD</modulo>
            </hora>
            <hora>
                <numero>6</numero>
                <hora_ini>20:15</hora_ini>
                <hora-fin>21:10</hora-fin>
                <modulo>PARE</modulo>
            </hora>
        </dia>
        <dia>
            <nombre>martes</nombre>
            <hora>
                <numero>1</numero>
                <hora_ini>15:20</hora_ini>
                <hora-fin>16:15</hora-fin>
                <modulo>GBD</modulo>
            </hora>
            <hora>
                <numero>2</numero>
                <hora_ini>16:15</hora_ini>
                <hora-fin>17:10</hora-fin>
                <modulo>FHW</modulo>
            </hora>            <hora>
                <numero>3</numero>
                <hora_ini>17:10</hora_ini>
                <hora-fin>18:05</hora-fin>
                <modulo>PARE</modulo>
            </hora>
            <hora>
                <recreo>18:05-18:25</recreo>
            </hora>
            <hora>
                <numero>4</numero>
                <hora_ini>18:25</hora_ini>
                <hora-fin>19:20</hora-fin>
                <modulo>LMSGI-TUTORIA</modulo>
            </hora>
            <hora>
                <numero>5</numero>
                <hora_ini>19:20</hora_ini>
                <hora-fin>20:15</hora-fin>
                <modulo>ISO</modulo>
            </hora>
            <hora>
                <numero>6</numero>
                <hora_ini>20:15</hora_ini>
                <hora-fin>21:10</hora-fin>
                <modulo>ISO</modulo>
            </hora>
        </dia>
        <dia>
            <nombre>miercoles</nombre>
            <hora>
                <numero>1</numero>
                <hora_ini>15:20</hora_ini>
                <hora-fin>16:15</hora-fin>
                <modulo>PARE</modulo>
            </hora>
            <hora>
                <numero>2</numero>
                <hora_ini>16:15</hora_ini>
                <hora-fin>17:10</hora-fin>
                <modulo>GBD</modulo>
            </hora>            
            <hora>
                <numero>3</numero>
                <hora_ini>17:10</hora_ini>
                <hora-fin>18:05</hora-fin>
                <modulo>ISO</modulo>
            </hora>
            <hora>
                <recreo>18:05-18:25</recreo>
            </hora>
            <hora>
                <numero>4</numero>
                <hora_ini>18:25</hora_ini>
                <hora-fin>19:20</hora-fin>
                <modulo>LMSGI</modulo>
            </hora>
            <hora>
                <numero>5</numero>
                <hora_ini>19:20</hora_ini>
                <hora-fin>20:15</hora-fin>
                <modulo>FOL</modulo>
            </hora>
            <hora>
                <numero>6</numero>
                <hora_ini>20:15</hora_ini>
                <hora-fin>21:10</hora-fin>
                <modulo>FOL</modulo>
            </hora>
        </dia>
        <dia>
            <nombre>jueves</nombre>
            <hora>
                <numero>1</numero>
                <hora_ini>15:20</hora_ini>
                <hora-fin>16:15</hora-fin>
                <modulo>ISO</modulo>
            </hora>
            <hora>
                <numero>2</numero>
                <hora_ini>16:15</hora_ini>
                <hora-fin>17:10</hora-fin>
                <modulo>ISO</modulo>
            </hora>            
            <hora>
                <numero>3</numero>
                <hora_ini>17:10</hora_ini>
                <hora-fin>18:05</hora-fin>
                <modulo>LMSGI</modulo>
            </hora>
            <hora>
                <recreo>18:05-18:25</recreo>
            </hora>
            <hora>
                <numero>4</numero>
                <hora_ini>18:25</hora_ini>
                <hora-fin>19:20</hora-fin>
                <modulo>GBD</modulo>
            </hora>
            <hora>
                <numero>5</numero>
                <hora_ini>19:20</hora_ini>
                <hora-fin>20:15</hora-fin>
                <modulo>PARE</modulo>
            </hora>
            <hora>
                <numero>6</numero>
                <hora_ini>20:15</hora_ini>
                <hora-fin>21:10</hora-fin>
                <modulo>PARE</modulo>
            </hora>
        </dia>
        <dia>
            <nombre>viernes</nombre>
            <hora>
                <numero>1</numero>
                <hora_ini>15:20</hora_ini>
                <hora-fin>16:15</hora-fin>
                <modulo>FHW</modulo>
            </hora>
            <hora>
                <numero>2</numero>
                <hora_ini>16:15</hora_ini>
                <hora-fin>17:10</hora-fin>
                <modulo>FHW</modulo>
            </hora>            
            <hora>
                <numero>3</numero>
                <hora_ini>17:10</hora_ini>
                <hora-fin>18:05</hora-fin>
                <modulo>PARE</modulo>
            </hora>
            <hora>
                <recreo>18:05-18:25</recreo>
            </hora>
            <hora>
                <numero>4</numero>
                <hora_ini>18:25</hora_ini>
                <hora-fin>19:20</hora-fin>
                <modulo>PARE</modulo>
            </hora>
            <hora>
                <numero>5</numero>
                <hora_ini>19:20</hora_ini>
                <hora-fin>20:15</hora-fin>
                <modulo>ISO</modulo>
            </hora>
            <hora>
                <numero>6</numero>
                <hora_ini>20:15</hora_ini>
                <hora-fin>21:10</hora-fin>
                <modulo>GBD</modulo>
            </hora>
        </dia>
    </dias>   
    </grupo>
    <modulo>
        <denominacion>1ºDAM</denominacion>
        <nombre_grado>desarrollo de aplicaciones multiplataforma</nombre_grado>
        <asignatura>
            <nombre>sistemas informaticos</nombre>
           <abreviatura>SSINF</abreviatura>
           <profesor>julio barbero</profesor>
           <horas>192h</horas> 
        </asignatura>
        <asignatura>
            <nombre>bases de datos</nombre>
           <abreviatura>BBDD</abreviatura>
           <profesor>puerto cruz</profesor>
           <horas>192h</horas> 
        </asignatura>
        <asignatura>
            <nombre>programacion</nombre>
           <abreviatura>PGRMC</abreviatura>
           <profesor>enrique pineda</profesor>
           <horas>224h</horas> 
        </asignatura>
        <modulos>
        <asignatura>
            <nombre>entornos de desarrollo</nombre>
           <abreviatura>ENTDL</abreviatura>
           <profesor>marcos fernandez</profesor>
           <horas>128h</horas> 
        </asignatura>
        <asignatura>
            <nombre>lenguaje de marca y sistemas gestion de inf</nombre>
           <abreviatura>LMSGI</abreviatura>
           <profesor>antonio berrocal</profesor>
           <horas>128h</horas> 
        </asignatura>
        <asignatura>
            <nombre>formacion y orientacion laboral</nombre>
           <abreviatura>FOL</abreviatura>
           <profesor>fatima hontiveros</profesor>
           <horas>96h</horas>
        </asignatura>
    </modulos>
